apiVersion: v2
name: renovate-helmv3-test
description: A Helm chart for testing renovate helmv3
type: application
version: 0.1.1
dependencies:
  - name: postgresql-ha
    version: 6.3.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
  - name: acs-engine-autoscaler
    version: 2.1.4
    repository: stable
    condition: acs-engine-autoscaler.enabled
