apiVersion: v2
name: renovate-helmv3-test
description: A Helm chart for testing renovate helmv3
type: application
version: 0.1.0
dependencies:
  - name: postgresql-ha
    version: 3.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
